# Dockerfile
FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=tungle
ENV N8N_BASIC_AUTH_PASSWORD=tungle@A1
ENV WEBHOOK_URL=https://n8n.onrender.com
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_EDITOR_BASE_URL=https://n8n.onrender.com/
